# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6bcdf37ce9acd2005d44ffe259aa2af7ccb0aae2a57897616fa48178f23a82ad8cff21628296523041061d02abe38c083f51e0906b71a5194627fc69a4723db4

test:
  secret_key_base: 264b904b2a559517d6fc1e857c1939db69224b20106c95012d97abff1bc243526556ba4cf98234ec36ea8a7793893a39c70250408aee54cd9b0865e00c02d561

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
